[tool.poetry]
name = "platinumshrimp"
version = "0.1.0"
description = ""
authors = ["Gustav Tiger <gustav@tiger.name>"]

[tool.poetry.dependencies]
python = "^3.6"
python-dateutil = "^2.8.1"
requests = "^2.22.0"
feedparser = "^5.2.1"
irc = "^18.0.0"
pyzmq = "^18.1.1"

[tool.poetry.dev-dependencies]
requests-mock = "^1.7.0"
black = "^20.8b1"
rope = "^0.18.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
